[build]
  command = """
    curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.39/quarto-1.6.39-linux-amd64.tar.gz
    mkdir -p ~/quarto
    tar -C ~/quarto -xzf quarto-1.6.39-linux-amd64.tar.gz
    export PATH=$PATH:~/quarto/quarto-1.6.39/bin
    quarto render
  """
  publish = "docs"

[build.environment]
  QUARTO_PRINT_STACK = "true"
